const gameboard = {
  board: [
    [
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
    [
      { ship: null, hit: false },
      { ship: "Carrier", hit: false },
      { ship: "Carrier", hit: false },
      { ship: "Carrier", hit: false },
      { ship: "Carrier", hit: false },
      { ship: "Carrier", hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
    [
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
    [
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
    [
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
    [
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
    [
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
    [
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
    [
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
    [
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
      { ship: null, hit: false },
    ],
  ],
  ships: [
    {
      name: "Carrier",
      size: 5,
      orientation: "horizontal",
      position: 12,
      isSunk: false,
    },
  ],
};

const stuff = gameboard.board[1][3];

console.log(stuff);
